version: "3"

volumes: 
  postgres_volume_local:
  postgres_volume_prod:

services: 
  pg-local:
    image: postgres:14-alpine3.17
    env_file: 
      - local.env
#    environment:
#      - PG_PASSWORD=admin
    ports:
      - "54321:5432"
    volumes:
      - postgres_volume_local:/var/lib/postgresql/data

  pg-prod:
    image: postgres:14-alpine3.17
    env_file:
      - prod.env
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=users
    ports:
      - "54322:5432"
    volumes:
      - postgres_volume_prod:/var/lib/postgresql/data

  migrator-local:
#   env_file: .env
    build: 
      context: .
      dockerfile: migration_local.Dockerfile
    restart: on-failure
    environment:
      DB_HOST: pg-local

  migrator-prod:
#   env_file: .env
    build: 
      context: .
      dockerfile: migration_prod.Dockerfile
    restart: on-failure
    environment:
      DB_HOST: pg-prod


